# Generated by Django 5.0.6 on 2024-06-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
